# Config file for automatic testing at travis-ci.org

language: python

cache:
  - pip
  - directories:
    - $HOME/protobuf

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get install libhdf5-serial-dev python-tables
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # for debugging

install:
  # Install scientific Python
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION numpy llvmlite scipy h5py
  - source activate testenv
  # Install protobuf
  - ./install_protobuf
  # Install other requirements
  - pip install -r requirements.txt
  - python setup.py install

script:
  - nosetests
  - flake8 acton --exclude *_pb2.py --max-line-length=80
